[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
members = ["vhdx-cli"]
resolver = "2"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

# Main library crate
[package]
name = "vhdx-rs"
version.workspace = true
edition.workspace = true
description = "VHDX (Virtual Hard Disk v2) library"

[lib]
name = "vhdx"

[dependencies]
uuid = { version = "1.23.1", features = ["v4"] }
thiserror = "2.0.18"
bitvec = "1.0.1"
crc32c = "0.6.8"
gpt_disk_io = { version = "0.16.2", optional = true }
gpt_disk_types = { version = "0.16.1", optional = true }

[features]
default = []
gpt = ["gpt_disk_io", "gpt_disk_types"]

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
