[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
authors = ["inschrift.spruch.raum <inschrift.spruch.raum@outlook.com>"]
license = "MIT"
repository = "https://github.com/inschrift-spruch-raum/vhdx-rs"
homepage = "https://github.com/inschrift-spruch-raum/vhdx-rs"
documentation = "https://github.com/inschrift-spruch-raum/vhdx-rs/tree/docs"
readme = "README.md"
publish = true
keywords = ["vhdx", "virtual-disk", "hyper-v"]
categories = ["filesystem", "parser-implementations"]

[workspace]
members = ["vhdx-cli"]
resolver = "2"

[workspace.dependencies]
tempfile = "3.27.0"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

# Main library crate
[package]
name = "vhdx-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "VHDX (Virtual Hard Disk v2) library"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "vhdx"

[dependencies]
uuid = { version = "1.23.2", features = ["v4"] }
thiserror = "2.0.18"
bitvec = "1.0.1"
crc32c = "0.6.8"
gpt_disk_io = { version = "0.16.2", optional = true }
gpt_disk_types = { version = "0.16.1", optional = true }

[features]
default = []
gpt = ["gpt_disk_io", "gpt_disk_types"]

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
