[package]
name = "vhdx-tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "VHDX (Virtual Hard Disk v2) CLI tool"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
publish.workspace = true
keywords.workspace = true
categories = ["command-line-utilities", "filesystem"]

[dependencies]
vhdx-rs = { version = "0.2.0", path = ".." }
clap = { version = "4.6.1", features = ["derive"] }
byte-unit = { version = "5.2.0", features = ["byte"] }

[dev-dependencies]
assert_cmd = "2.2.2"
tempfile.workspace = true
predicates = "3.1.4"

[lints]
workspace = true
